import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1737303508082 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."reward_status" AS ENUM('ACTIVE', 'HOLD')`);

        await queryRunner.query(`ALTER TABLE rewards ADD COLUMN "initial_quantity" bigint NOT NULL DEFAULT 0`);
        // update status column
        await queryRunner.query(`ALTER TABLE rewards ADD COLUMN "status" "public"."reward_status" NULL DEFAULT 'ACTIVE'`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE rewards DROP COLUMN "initial_quantity"`);
        await queryRunner.query(`ALTER TABLE rewards DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."reward_status"`);  
        
    }

}
