import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1740387775201 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TYPE "reward_vip_status" ADD VALUE 'REJECT'`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    }

}
