export enum StatusCanNotLogin {
  USER_DELETED_OR_BANNER = 'USER_DELETED_OR_BANNER',
  USER_WAITING_VERIFY = 'USER_WAITING_VERIFY',
  EMAIL_HAS_LINKED_SOCIAL = 'EMAIL_HAS_LINKED_SOCIAL',
}

export enum StatusCanNotRegister {
  USER_DELETED_OR_BANNER = 'USER_DELETED_OR_BANNER',
  USER_WAITING_VERIFY = 'USER_WAITING_VERIFY',
  EMAIL_HAS_LINKED_SOCIAL = 'EMAIL_HAS_LINKED_SOCIAL',
  EMAIL_EXISTED = 'EMAIL_EXISTED',
}

export enum StatusCanNotSendOTP {
  USER_DELETED_OR_BANNER = 'USER_DELETED_OR_BANNER',
  USER_READY_VERIFY = 'USER_READY_VERIFY',
  USER_WAITING_VERIFY = 'USER_WAITING_VERIFY',
}
