export enum AuthError {
    INVALID_MYMOBIFONE_ACCOUNT = 'INVALID_MYMOBIFONE_ACCOUNT',
    INVALID_MYPOINT_ACCOUNT = 'INVALID_MYPOINT_ACCOUNT',
    GET_MMBF_TOTAL_TURN_FAILED = 'GET_MMBF_TOTAL_TURN_FAILED',
}