export enum CampaignError {
    ALREADY_EXISTS_CAMPAIGN = 'ALREADY_EXISTS_CAMPAIGN',
    DEFAULT_MASTER_DATA_NOT_FOUND = 'DEFAULT_MASTER_DATA_NOT_FOUND',
    CAMPAIGN_NOT_FOUND = 'CAMPAIGN_NOT_FOUND',
}