export enum ErrorCode {
  PUBLIC_API_NOT_FOUND = 'PUBLIC_API_NOT_FOUND',
  INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
  MERCHANT_NOT_FOUND = 'MERCHANT_NOT_FOUND',
  TICKET_NOT_FOUND = 'TICKET_NOT_FOUND',
  INVALID_API_KEY_OR_TENANT_CODE = 'INVALID_API_KEY_OR_TENANT_CODE',
  API_KEY_NOT_FOUND = 'API_KEY_NOT_FOUND',
  ACTION_NOT_FOUND = 'ACTION_NOT_FOUND',
}
