export enum RewardError {
    DEFAULT_MASTER_DATA_NOT_FOUND = 'DEFAULT_MASTER_DATA_NOT_FOUND',
    RATING_EXCEED = 'RATING_EXCEED',
    CREATE_REWARD_FAILED = 'CREATE_REWARD_FAILED',
    CAMPAIGN_NOT_FOUND = 'CAMPAIGN_NOT_FOUND',
}