export enum RewardError {
    DEFAULT_MASTER_DATA_NOT_FOUND = 'DEFAULT_MASTER_DATA_NOT_FOUND',
    RATING_EXCEED = 'RATING_EXCEED',
    CREATE_REWARD_FAILED = 'CREATE_REWARD_FAILED',
    CAMPAIGN_NOT_FOUND = 'CAMPAIGN_NOT_FOUND',
    REWARDS_EMPTY = 'REWARDS_EMPTY',
    INVALID_TOTAL_RATING = 'INVALID_TOTAL_RATING',
    REWARD_NOT_FOUND = 'REWARD_NOT_FOUND',
    REWARD_OUT_OF_STOCK = 'REWARD_OUT_OF_STOCK',
    REWARD_CRAFT_NOT_MATCH = 'REWARD_CRAFT_NOT_MATCH',
    MISSING_REWARD_MASTER_DATA = 'MISSING_REWARD_MASTER_DATA',
}